Avoid apt environment creation for non root commands

diff --git a/install/bin/llx-apt b/install/bin/llx-apt
--- a/install/bin/llx-apt
+++ b/install/bin/llx-apt
@@ -134,7 +134,9 @@ main(){
 		echo "DEBUG: Command to run"
 		echo "       apt $LLX_APT_EXTRA $USER_CMD_ARGS"
 	else
-		create_environment || die "Failed to create apt environment"
+		if [ "$LLX_ROOT_REQUIRED" ] ; then
+			create_environment || die "Failed to create apt environment"
+		fi
 		apt $LLX_APT_EXTRA $USER_CMD_ARGS
 	fi
 }
